apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: devops-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: felipevarejao/hello-world:v2
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: hello-world-config
              key: message
        - name: FAKE-SECRET-USERNAME
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: username
        - name: FAKE-SECRET-PASSWORD
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: password